local CDEV_CDN <const> = "https://static.cdev.shop/resources/emotemenu/expressions/"

Expressions = {
    {
        id = "angry",
        label = "Angry",
        thumbnailcdn = CDEV_CDN .. "angry.webp",
        expression = "mood_angry_1",
        category = "expressions",
    },
    {
        id = "drunk",
        label = "Drunk",
        expression = "mood_drunk_1",
        thumbnailcdn = CDEV_CDN .. "drunk.webp",
        category = "expressions",
    },
    {
        id = "dumb",
        label = "Dumb",
        expression = "pose_injured_1",
        thumbnailcdn = CDEV_CDN .. "dumb.webp",
        category = "expressions",
    },
    {
        id = "electrocuted",
        label = "Electrocuted",
        expression = "electrocuted_1",
        thumbnailcdn = CDEV_CDN .. "electrocuted.webp",
        category = "expressions",
    },
    {
        id = "grumpy",
        label = "Grumpy",
        expression = "effort_1",
        thumbnailcdn = CDEV_CDN .. "grumpy.webp",
        category = "expressions",
    },
    {
        id = "grumpy2",
        label = "Grumpy2",
        expression = "mood_drivefast_1",
        thumbnailcdn = CDEV_CDN .. "grumpy2.webp",
        category = "expressions",
    },
    {
        id = "grumpy3",
        label = "Grumpy3",
        expression = "pose_angry_1",
        thumbnailcdn = CDEV_CDN .. "grumpy3.webp",
        category = "expressions",
    },
    {
        id = "happy",
        label = "Happy",
        expression = "mood_happy_1",
        thumbnailcdn = CDEV_CDN .. "happy.webp",
        category = "expressions",
    },
    {
        id = "injured",
        label = "Injured",
        expression = "mood_injured_1",
        thumbnailcdn = CDEV_CDN .. "injured.webp",
        category = "expressions",
    },
    {
        id = "joyful",
        label = "Joyful",
        expression = "mood_dancing_low_1",
        thumbnailcdn = CDEV_CDN .. "joyful.webp",
        category = "expressions",
    },
    {
        id = "mouthbreather",
        label = "Mouthbreather",
        expression = "smoking_hold_1",
        thumbnailcdn = CDEV_CDN .. "mouthbreather.webp",
        category = "expressions",
    },
    {
        id = "neverblink",
        label = "Never Blink",
        expression = "pose_normal_1",
        thumbnailcdn = CDEV_CDN .. "neverblink.webp",
        category = "expressions",
    },
    {
        id = "oneeye",
        label = "One Eye",
        expression = "pose_aiming_1",
        thumbnailcdn = CDEV_CDN .. "oneeye.webp",
        category = "expressions",
    },
    {
        id = "shocked",
        label = "Shocked",
        expression = "shocked_1",
        thumbnailcdn = CDEV_CDN .. "shocked.webp",
        category = "expressions",
    },
    {
        id = "shocked2",
        label = "Shocked2",
        expression = "shocked_2",
        thumbnailcdn = CDEV_CDN .. "shocked2.webp",
        category = "expressions",
    },
    {
        id = "sleeping",
        label = "Sleeping",
        expression = "mood_sleeping_1",
        thumbnailcdn = CDEV_CDN .. "sleeping.webp",
        category = "expressions",
    },
    {
        id = "sleeping2",
        label = "Sleeping2",
        expression = "dead_1",
        thumbnailcdn = CDEV_CDN .. "sleeping2.webp",
        category = "expressions",
    },
    {
        id = "sleeping3",
        label = "Sleeping3",
        expression = "dead_2",
        thumbnailcdn = CDEV_CDN .. "sleeping3.webp",
        category = "expressions",
    },
    {
        id = "smug",
        label = "Smug",
        expression = "mood_smug_1",
        thumbnailcdn = CDEV_CDN .. "smug.webp",
        category = "expressions",
    },
    {
        id = "speculative",
        label = "Speculative",
        expression = "mood_aiming_1",
        thumbnailcdn = CDEV_CDN .. "speculative.webp",
        category = "expressions",
    },
    {
        id = "stressed",
        label = "Stressed",
        expression = "mood_stressed_1",
        thumbnailcdn = CDEV_CDN .. "stressed.webp",
        category = "expressions",
    },
    {
        id = "sulking",
        label = "Sulking",
        expression = "mood_sulk_1",
        thumbnailcdn = CDEV_CDN .. "sulking.webp",
        category = "expressions",
    },
    {
        id = "weird",
        label = "Weird",
        expression = "effort_2",
        thumbnailcdn = CDEV_CDN .. "weird.webp",
        category = "expressions",
    },
    {
        id = "weird2",
        label = "Weird2",
        expression = "effort_3",
        thumbnailcdn = CDEV_CDN .. "weird2.webp",
        category = "expressions",
    },
}