local CDEV_CDN <const> = "https://static.cdev.shop/resources/emotemenu/walkstyles/"

WalkStyles = {
    {
        id = "alien",
        label = "Alien",
        clipSet = "MOVE_M@ALIEN",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "alien.webp",
    },
    {
        id = "armored",
        label = "Armored",
        clipSet = "ANIM_GROUP_MOVE_BALLISTIC",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "armored.webp",
    },
    {
        id = "arrogant",
        label = "Arrogant",
        clipSet = "MOVE_F@ARROGANT@A",
        category = "walkstyles",
        thumbnailcdn  = CDEV_CDN .. "arrogant.webp",
    },
    {
        id = "brave",
        label = "Brave",
        clipSet = "MOVE_M@BRAVE",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "brave.webp",
    },
    {
        id = "casual",
        label = "Casual",
        clipSet = "MOVE_M@CASUAL@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "casual.webp",
    },
    {
        id = "casual2",
        label = "Casual 2",
        clipSet = "MOVE_M@CASUAL@B",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "casual2.webp",
    },
    {
        id = "casual3",
        label = "Casual 3",
        clipSet = "MOVE_M@CASUAL@C",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "casual3.webp",
    },
    {
        id = "casual4",
        label = "Casual 4",
        clipSet = "MOVE_M@CASUAL@D",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "casual4.webp",
    },
    {
        id = "casual5",
        label = "Casual 5",
        clipSet = "MOVE_M@CASUAL@E",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "casual5.webp",
    },
    {
        id = "casual6",
        label = "Casual 6",
        clipSet = "MOVE_M@CASUAL@F",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "casual6.webp",
    },
    {
        id = "chichi",
        label = "Chichi",
        clipSet = "MOVE_F@CHICHI",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "chichi.webp",
    },
    {
        id = "confident",
        label = "Confident",
        clipSet = "MOVE_M@CONFIDENT",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "confident.webp",
    },
    {
        id = "cop",
        label = "Cop",
        clipSet = "MOVE_M@BUSINESS@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "cop.webp",
    },
    {
        id = "cop2",
        label = "Cop 2",
        clipSet = "MOVE_M@BUSINESS@B",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "cop2walkstyle.webp",
    },
    {
        id = "cop3",
        label = "Cop 3",
        clipSet = "MOVE_M@BUSINESS@C",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "cop3.webp",
    },
    {
        id = "default_female",
        label = "Default Female",
        clipSet = "MOVE_F@MULTIPLAYER",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "default_female.webp",
    },
    {
        id = "default_male",
        label = "Default Male",
        clipSet = "MOVE_M@MULTIPLAYER",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "default_male.webp",
    },
    {
        id = "drunk",
        label = "Drunk",
        clipSet = "MOVE_M@DRUNK@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "drunk.webp",
    },
    {
        id = "drunk2",
        label = "Drunk 2",
        clipSet = "MOVE_M@BUZZED",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "drunk2.webp",
    },
    {
        id = "drunk3",
        label = "Drunk 3",
        clipSet = "MOVE_M@DRUNK@VERYDRUNK",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "drunk3.webp",
    },
    {
        id = "femme",
        label = "Femme",
        clipSet = "MOVE_F@FEMME@",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "femme.webp",
    },
    {
        id = "fire",
        label = "Fire",
        clipSet = "MOVE_CHARACTERS@FRANKLIN@FIRE",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "fire.webp",
    },
    {
        id = "fire2",
        label = "Fire 2",
        clipSet = "MOVE_CHARACTERS@MICHAEL@FIRE",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "fire2.webp",
    },
    {
        id = "fire3",
        label = "Fire 3",
        clipSet = "MOVE_M@FIRE",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "fire3.webp",
    },
    {
        id = "flee",
        label = "Flee",
        clipSet = "MOVE_F@FLEE@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "flee.webp",
    },
    {
        id = "franklin",
        label = "Franklin",
        clipSet = "MOVE_P_M_ONE",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "franklin.webp",
    },
    {
        id = "gangster",
        label = "Gangster",
        clipSet = "MOVE_M@GANGSTER@GENERIC",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "gangster.webp",
    },
    {
        id = "gangster2",
        label = "Gangster 2",
        clipSet = "MOVE_M@GANGSTER@NG",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "gangster2.webp",
    },
    {
        id = "gangster3",
        label = "Gangster 3",
        clipSet = "MOVE_M@GANGSTER@VAR_E",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "gangster3.webp",
    },
    {
        id = "gangster4",
        label = "Gangster 4",
        clipSet = "MOVE_M@GANGSTER@VAR_F",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "gangster4.webp",
    },
    {
        id = "gangster5",
        label = "Gangster 5",
        clipSet = "MOVE_M@GANGSTER@VAR_I",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "gangster5.webp",
    },
    {
        id = "guard",
        label = "Guard",
        clipSet = "MOVE_M@PRISON_GAURD",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "guard.webp",
    },
    {
        id = "handcuffs",
        label = "Handcuffs",
        clipSet = "MOVE_M@PRISONER_CUFFED",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "handcuffs.webp",
    },
    {
        id = "heels",
        label = "Heels",
        clipSet = "MOVE_F@HEELS@C",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "heels.webp",
    },
    {
        id = "heels2",
        label = "Heels 2",
        clipSet = "MOVE_F@HEELS@D",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "heels2.webp",
    },
    {
        id = "hiking",
        label = "Hiking",
        clipSet = "MOVE_M@HIKING",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "hiking.webp",
    },
    {
        id = "hipster",
        label = "Hipster",
        clipSet = "MOVE_M@HIPSTER@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "hipster.webp",
    },
    {
        id = "hobo",
        label = "Hobo",
        clipSet = "MOVE_M@HOBO@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "hobo.webp",
    },
    {
        id = "hurry",
        label = "Hurry",
        clipSet = "MOVE_F@HURRY@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "hurry.webp",
    },
    {
        id = "janitor",
        label = "Janitor",
        clipSet = "MOVE_P_M_ZERO_JANITOR",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "janitor.webp",
    },
    {
        id = "janitor2",
        label = "Janitor 2",
        clipSet = "MOVE_P_M_ZERO_SLOW",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "janitor2.webp",
    },
    {
        id = "jog",
        label = "Jog",
        clipSet = "MOVE_M@JOG@",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "jog.webp",
    },
    {
        id = "lemar",
        label = "Lemar",
        clipSet = "ANIM_GROUP_MOVE_LEMAR_ALLEY",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "lemar.webp",
    },
    {
        id = "lester",
        label = "Lester",
        clipSet = "MOVE_HEIST_LESTER",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "lester.webp",
    },
    {
        id = "lester2",
        label = "Lester 2",
        clipSet = "MOVE_LESTER_CANEUP",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "lester2.webp",
    },
    {
        id = "maneater",
        label = "Maneater",
        clipSet = "MOVE_F@MANEATER",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "maneater.webp",
    },
    {
        id = "michael",
        label = "Michael",
        clipSet = "MOVE_PED_BUCKET",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "michael.webp",
    },
    {
        id = "money",
        label = "Money",
        clipSet = "MOVE_M@MONEY",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "money.webp",
    },
    {
        id = "muscle",
        label = "Muscle",
        clipSet = "MOVE_M@MUSCLE@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "muscle.webp",
    },
    {
        id = "posh",
        label = "Posh",
        clipSet = "MOVE_M@POSH@",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "posh.webp",
    },
    {
        id = "posh2",
        label = "Posh 2",
        clipSet = "MOVE_F@POSH@",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "posh2.webp",
    },
    {
        id = "quick",
        label = "Quick",
        clipSet = "MOVE_M@QUICK",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "quick.webp",
    },
    {
        id = "runner",
        label = "Runner",
        clipSet = "FEMALE_FAST_RUNNER",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "runner.webp",
    },
    {
        id = "sad",
        label = "Sad",
        clipSet = "MOVE_M@SAD@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "sad.webp",
    },
    {
        id = "sassy",
        label = "Sassy",
        clipSet = "MOVE_M@SASSY",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "sassy.webp",
    },
    {
        id = "sassy2",
        label = "Sassy 2",
        clipSet = "MOVE_F@SASSY",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "sassy2.webp",
    },
    {
        id = "scared",
        label = "Scared",
        clipSet = "MOVE_F@SCARED",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "scared.webp",
    },
    {
        id = "sexy",
        label = "Sexy",
        clipSet = "MOVE_F@SEXY@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "sexy.webp",
    },
    {
        id = "shady",
        label = "Shady",
        clipSet = "MOVE_M@SHADYPED@A",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "shady.webp",
    },
    {
        id = "slow",
        label = "Slow",
        clipSet = "MOVE_CHARACTERS@JIMMY@SLOW@",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "slow.webp",
    },
    {
        id = "swagger",
        label = "Swagger",
        clipSet = "MOVE_M@SWAGGER",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "swagger.webp",
    },
    {
        id = "tough",
        label = "Tough",
        clipSet = "MOVE_M@TOUGH_GUY@",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "tough.webp",
    },
    {
        id = "tough2",
        label = "Tough 2",
        clipSet = "MOVE_F@TOUGH_GUY@",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "tough2.webp",
    },
    {
        id = "trash",
        label = "Trash",
        clipSet = "CLIPSET@MOVE@TRASH_FAST_TURN",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "trash.webp",
    },
    {
        id = "trash2",
        label = "Trash 2",
        clipSet = "MISSFBI4PREPP1_GARBAGEMAN",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "trash2.webp",
    },
    {
        id = "trevor",
        label = "Trevor",
        clipSet = "MOVE_P_M_TWO",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "trevor.webp",
    },
    {
        id = "wide",
        label = "Wide",
        clipSet = "MOVE_M@BAG",
        category = "walkstyles",
        thumbnailcdn = CDEV_CDN .. "wide.webp",
    },
    
}