QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civil', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelance', payment = 10 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 50 } } },
	judge = { label = 'Magistrat', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Juge', payment = 100 } } },
	lawyer = { label = 'Cabinet d\'avocats', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associé', payment = 50 } } },
	reporter = { label = 'Journaliste', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Reporter', payment = 50 } } },
	trucker = { label = 'Routier', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 50 } } },
	tow = { label = 'Dépannage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 50 } } },
	garbage = { label = 'Éboueur', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Ramasseur', payment = 50 } } },
	vineyard = { label = 'Vignoble', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Cueilleur', payment = 50 } } },
	hotdog = { label = 'Hot-dog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Vendeur', payment = 50 } } },


	police = {
		label = 'Force de l\'ordre',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Officier', payment = 75 },
			['2'] = { name = 'Sergent', payment = 100 },
			['3'] = { name = 'Lieutenant', payment = 125 },
			['4'] = { name = 'Chef', isboss = true, payment = 150 },
		},
	},
	ambulance = {
		label = 'SAMU',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Infirmier', payment = 75 },
			['2'] = { name = 'Docteur', payment = 100 },
			['3'] = { name = 'Chirurgien', payment = 125 },
			['4'] = { name = 'Chef', isboss = true, payment = 150 },
		},
	},
	realestate = {
		label = 'Agent Immobilier',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Promoteur', payment = 75 },
			['2'] = { name = 'Promoteur', payment = 100 },
			['3'] = { name = 'Promoteur', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Chauffeur', payment = 75 },
			['2'] = { name = 'Chauffeur', payment = 100 },
			['3'] = { name = 'Manager', payment = 125 },
			['4'] = { name = 'Chef', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Concessionnaire',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Vendeur', payment = 75 },
			['2'] = { name = 'Directeur des ventes', payment = 100 },
			['3'] = { name = 'Directeur adjoint', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'Garagiste',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Expérimenté', payment = 100 },
			['3'] = { name = 'Avancé', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
}
